global using System.ComponentModel.DataAnnotations;
global using System.Net;
global using System.Text;
global using AutoMapper;
global using MagicVilla_Web.Models;
global using MagicVilla_Web.Models.Dto;
global using MagicVilla_Web.Services;
global using MagicVilla_Web.Services.IServices;
global using Microsoft.AspNetCore.Mvc;
global using Newtonsoft.Json;
global using static MagicVilla_Utility.SD;
